### ISSUE TITLE
What is account_name?

### ISSUE THREAD

**Issue by plajjan** [sartura/sip-plugin#1]
I wonder what the purpose of the leaf "account_name" is? The key of the list is "account" which already seems to be a name for the account, so how is that different from "account_name" ?

**Comment by mislavn** [comment]
Account name is the option `option name 'PANTERA-2'` while account is the name of the config section `config sip_service_provider 'sip1'`.

At the moment this YANG model requires some knowledge of the UCI config file, I would like to remove this or make it implicit but I'm not sure how to model the YANG model due to my lack of SIP knowledge.

**Comment by mislavn** [comment]
An example of the voice_client UCI config file you can find at: https://github.com/sartura/sip-plugin/blob/devel/docker/voice_client

The name of the config section sip_service_provider (sip1) is need in order to parse the UCI config file.
